### ISSUE TITLE
Some images are missing

### ISSUE THREAD

**Issue by jonschaapkoe** [Giocrom/Game-Of-Life-pygame#1]
In global_vars.py are some images loaded in from the docs folder which are not in the docs folder:
img_blinker_h = pygame.image.load("Docs/blinker_horizontal36x36.png")
img_spaceships_bottomright = pygame.image.load("Docs/spaceships_bottomright36x36.png")
img_spaceships_upright = pygame.image.load("Docs/spaceships_upright36x36.png")
img_spaceships_upleft = pygame.image.load("Docs/spaceships_upleft36x36.png")
img_spaceships_bottomleft = pygame.image.load("Docs/spaceships_bottomleft36x36.png")

**Comment by giosue-rasi** [comment]
Must have missed them while uploading the "Docs" folder, I'll fix the problem immediately!
